name: ERPNext Deploy to VPS

on:
  push:
    branches:
      - erpnext-v16

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code from GitHub
        uses: actions/checkout@v4

      - name: Deploy via SSH Password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 85.190.254.51
          username: dressup
          password: "701865"
          port: 22
          script_stop: true
          script: |
            export PATH=$PATH:/home/dressup/.local/bin:/usr/local/bin
            cd ~/frappe-bench
            
            # Get the app from the specific branch
            bench get-app --overwrite --branch erpnext-v16 https://github.com/sadikhossainnub/erpnext.git
            
            # Run database migrations for site
            bench --site erp.dressup.com.bd migrate
            
            # Clear cache
            bench --site erp.dressup.com.bd clear-cache
