name: ERPNext Deploy to VPS

on:
  push:
    branches:
      - erpnext-v16

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code from GitHub
        uses: actions/checkout@v4

      - name: Deploy via SSH Password
        # Warning: Storing plain text password in this file is a security risk.
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 85.190.254.51
          username: dressup
          password: "701865"
          port: 22
          script_stop: true
          script: |
            # Navigate to your frappe-bench directory (Commonly in Home)
            cd ~/frappe-bench
            
            # Pull updates for erpnext app
            bench update --pull --apps erpnext
            
            # Run database migrations
            bench migrate
            
            # Clear cache
            bench clear-cache
            
            # Restart bench services
            bench restart
